### ISSUE TITLE
HTTP API URL? 

### ISSUE THREAD

**Issue by aneesh-neelam** [biocross/VITCloud#1]
What's the URL and the HTTP Request Method?

**Comment by sreeram-dev** [comment]
where?

**Comment by biocross** [comment]
http://vitcloud-biocross.rhcloud.com/interface
HTTP Method: POST

**Comment by aneesh-neelam** [comment]
Alright, thanks. Add the website URL at the description of the repository please? 

The Windows Desktop Application's repository is [here](https://github.com/aneesh-neelam/VITcloud-Client-Windows).
